export { firstJoke, spanLeft, spanRight, spanTop, spanBottom, newJoke, firstPartJoke, buttonResponse, result, reviews, reportJokes, firstPart, secondPart };
// const buttonTopJoke: HTMLElement | null = document.querySelector('.buttonTopJoke');
const firstJoke = document.getElementById('firstJoke');
const spanLeft = document.getElementById('spanLeft');
const spanRight = document.getElementById('spanRight');
const spanTop = document.getElementById('spanTop');
const spanBottom = document.getElementById('spanBottom');
const newJoke = document.getElementById('newJoke');
const firstPartJoke = document.getElementById('firstPartJoke');
const firstPart = document.getElementById('firstPart');
const secondPart = document.getElementById('secondPart');
const buttonResponse = document.getElementById('buttonResponse');
const result = document.getElementById('result');
const reviews = document.querySelectorAll('.review');
const reportJokes = [];
